resources:
  - name: src
    type: git
    source:
      uri: https://github.com/aaa-ncnu-ie/securityTests.git
      branch: master
  - name: timer
    type: time
    source:
      interval: 60m

jobs:
- name: test
  plan:
  - get: src
    trigger: false
  - get: timer
    trigger: true
  - task: test
    file: src/securitytest.yml
