platform: linux

image_resources:
    type: docker
    source:
      repository: tgbenson/gauntlt
      tag: latest

resources:
  - name: timer
    type: time
    source:
      interval: 60m

jobs:
- name: securityTests
  plan:
  - get: timer
    trigger: true
  - task: run-security-tests
    file: /opt/securityTests/securitytest.yml 
