resource_types:
- name: slack-notifications
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
  - name: gauntlt-repo
    type: git
    source: 
      uri: https://github.com/aaa-ncnu-ie/securityTests.git

  - name: timer
    type: time
    source:
      interval: 60m

  - name: slack-alert
    type: slack-notifications
    source:
      url: https://hooks.slack.com/services/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


jobs:
  - name: securityTest-e3
    plan:
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: csaa/security-gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/e3-SecurityTestCases.sh
      on_failure:
        put: slack-alert
        params:
          always_notify: true
          icon_emoji: ":ship:"
          channel: "#security"
          text_file: ci/last_commit_hash
          text: |
            Security test, failures - e3
  - name: securityTest-e2
    plan:
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: csaa/security-gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/e2-SecurityTestCases.sh
      on_failure:
        put: slack-alert
        params:
          always_notify: true
          icon_emoji: ":ship:"
          channel: "#security"
          text_file: ci/last_commit_hash
          text: |
            Security test, failures - e2
  - name: securityTest-e1
    plan:
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: csaa/security-gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/e1-SecurityTestCases.sh
      on_failure:
        put: slack-alert
        params:
          always_notify: true
          icon_emoji: ":ship:"
          channel: "#security"
          text_file: ci/last_commit_hash
          text: |
            Security test, failures - e1
  - name: securityTest-quote    
    plan:
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: csaa/security-gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/quote-SecurityTestCases.sh
      on_failure:
        put: slack-alert
        params:
          always_notify: true
          icon_emoji: ":ship:"
          channel: "#security"
          text_file: ci/last_commit_hash
          text: |
            Security test, failures - quote
  - name: securityTest-prod    
    plan:
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: csaa/security-gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/prod-SecurityTestCases.sh
      on_failure:
        put: slack-alert
        params:
          always_notify: true
          icon_emoji: ":ship:"
          channel: "#security"
          text_file: ci/last_commit_hash
          text: |
            Security test, failures - prod

