resource_types:
- name: slack-notifications
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
  - name: gauntlt-repo
    type: git
    source: 
      uri: https://github.com/aaa-ncnu-ie/securityTests.git

  - name: timer
    type: time
    source:
      interval: 60m

  - name: slack-alert
    type: slack-notifications
    source:
      url: https://hooks.slack.com/services/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


jobs:
  - name: e3
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/e3-SecurityTestCases.sh
      on_failure:
        put: slack-alert
        params:
          always_notify: true
          icon_emoji: ":ship:"
          channel: "#security"
          text_file: ci/last_commit_hash
          text: |
            Security test, failures - e3
      on_success:
        put: slack-alert
        params:
          channel: "#security"
          always_notify: true
          icon_emoji: ":ship:"
          text_file: ./cardinal-repo/ci/last_commit_hash
          text: |
            Security test, success - e3

  - name: e2
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/e2-SecurityTestCases.sh
      on_failure:
        put: slack-alert
        params:
          always_notify: true
          icon_emoji: ":ship:"
          channel: "#security"
          text_file: ci/last_commit_hash
          text: |
            Security test, failures - e2
      on_success:
        put: slack-alert
        params:
          channel: "#security"
          always_notify: true
          icon_emoji: ":ship:"
          text_file: ./cardinal-repo/ci/last_commit_hash
          text: |
            Security test, success - e2

  - name: e1
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/e1-SecurityTestCases.sh
      on_failure:
        put: slack-alert
        params:
          always_notify: true
          icon_emoji: ":ship:"
          channel: "#security"
          text_file: ci/last_commit_hash
          text: |
            Security test, failures - e1
      on_success:
        put: slack-alert
        params:
          channel: "#security"
          always_notify: true
          icon_emoji: ":ship:"
          text_file: ./cardinal-repo/ci/last_commit_hash
          text: |
            Security test, success - e1

  - name: quote    
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/quote-SecurityTestCases.sh
      on_failure:
        put: slack-alert
        params:
          always_notify: true
          icon_emoji: ":ship:"
          channel: "#security"
          text_file: ci/last_commit_hash
          text: |
            Security test, failures - quote
      on_success:
        put: slack-alert
        params:
          channel: "#security"
          always_notify: true
          icon_emoji: ":ship:"
          text_file: ./cardinal-repo/ci/last_commit_hash
          text: |
            Security test, success - quote

  - name: prod    
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/prod-SecurityTestCases.sh
      on_failure:
        put: slack-alert
        params:
          always_notify: true
          icon_emoji: ":ship:"
          channel: "#security"
          text_file: ci/last_commit_hash
          text: |
            Security test, failures - prod
      on_success:
        put: slack-alert
        params:
          channel: "#security"
          always_notify: true
          icon_emoji: ":ship:"
          text_file: ./cardinal-repo/ci/last_commit_hash
          text: |
            Security test, success - prod

