resources:
  - name: gauntlt-repo
    type: git
    source: 
      uri: https://github.com/aaa-ncnu-ie/securityTests.git
  - name: timer
    type: time
    source:
      interval: 60m

jobs:
  - name: securityTests
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: ./gauntlt-repo/concourseSecurityTestCases.sh
