resources:
  - name: git-securitytests-repo
    type: git
    source: 
      uri: https://github.com/aaa-ncnu-ie/securityTests.git

  - name: timer
    type: time
    source:
      interval: 60m
      
  - name: security-image
    type: docker-image
    source:
      repository: tgbenson/securitytests
      tag: latest

  - name: slack-alert
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/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

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest


jobs:
  - name: run-security-tests
    plan:
    - aggregate:
      - get: git-securitytests-repo
        trigger: false
      - get: security-image
        trigger: false
      - get: timer
        trigger: true
    - aggregate:
      - task: run-tests-e1
        inputs:
        - name: git-securitytests-repo
        image: security-image
        file: git-securitytests-repo/ci/perf.yml
        params:
          HOSTNAME: e1.pncie.com
      - task: run-tests-e2
        inputs:
        - name: git-securitytests-repo
        image: security-image
        file: git-securitytests-repo/ci/perf.yml
        params:
          HOSTNAME: e2.pncie.com  
      - task: run-tests-e3
        inputs:
        - name: git-securitytests-repo
        image: security-image
        file: git-securitytests-repo/ci/perf.yml
        params:
          HOSTNAME: e3.pncie.com
      - task: run-tests-prod
        inputs:
        - name: git-securitytests-repo
        image: security-image
        file: git-securitytests-repo/ci/prod.yml
        params:
          HOSTNAME: csaa-insurance.aaa.com  
#      - task: run-tests-quote
#        inputs:
#        - name: git-securitytests-repo
#        image: securitytests-image
#        file: git-securitytests-repo/ci/quote.yml
#        params:
#          HOSTNAME: quote.digital.pncie.com           
    on_failure:
      put: slack-alert
      params:
        always_notify: true
        icon_emoji: ":exclamation:"
        channel: '#secops'
        text: |
          Security checks/tests failed
          Details of execution:
          http://concoursedev.tent.trt.csaa.pri/builds/$BUILD_ID
  - name: run-security-checks
    plan:
    - aggregate:
      - get: timer
        trigger: true
      - get: securitytests-repo
        resource: git-securitytests-repo
        trigger: false
      - get: security-image
#    - task: run-securitytests-quote
#      inputs:
#      - name: securitytests-repo
#      file: securitytests-repo/ci/check.yml
#      image: securitytests-image
#      params: 
#        DATADOG_APIKEY: 8a91bd828137db6e599e3932c20ef336
#        DATADOG_APPKEY: 249629b031233b4c14fd129cf74c03bebb77b8e8
#        URLS: quoteMasterURLList.txt
#        APP: quote
#        SERVER: quote.digital.pncie.com
#        ACCESS: quoteAccessControl.txt
#        UNENCRYPT: quoteUnencryptControl.txt
    - task: run-securitytests-prod
      inputs:
       - name: securitytests-repo
      file: securitytests-repo/ci/check.yml
      image: security-image 
      params: 
        DATADOG_APIKEY: 8a91bd828137db6e599e3932c20ef336
        DATADOG_APPKEY: 249629b031233b4c14fd129cf74c03bebb77b8e8
        URLS: csaaMasterURLList.txt
        APP: prod
        SERVER: csaa-insurance.aaa.com 
        ACCESS: csaaaccessControl.txt
        UNENCRYPT: csaaunencryptControl.txt
    on_failure:
      put: slack-alert
      params:
        always_notify: true
        icon_emoji: ":exclamation:"
        channel: '#secops'
        text: |
          Security checks failed
          Details of execution:
          http://concoursedev.tent.trt.csaa.pri/builds/$BUILD_ID
