resources:
  - name: gauntlt-repo
    type: git
    source: 
      uri: https://github.com/aaa-ncnu-ie/securityTests.git
  - name: timer
    type: time
    source:
      interval: 60m

jobs:
  - name: e3
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/e3-SecurityTestCases.sh
  - name: e2
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/e2-SecurityTestCases.sh
  - name: e1
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/e1-SecurityTestCases.sh
  - name: quote    
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/quote-SecurityTestCases.sh
  - name: prod    
    plan:
    - get: timer
      trigger: true
    - get: gauntlt-repo
    - task: run-tests
      config:
        platform: linux
        inputs:
        - name: gauntlt-repo
        image_resource:
          type: docker-image
          source:
            repository: tgbenson/gauntlt
            tag: latest
        run: 
          path: gauntlt-repo/prod-SecurityTestCases.sh
