resources:
  - name: git-securitytests-repo
    type: git
    source: 
      uri: https://github.com/aaa-ncnu-ie/securityTests.git

  - name: securitytests-image
    type: docker-image
    source:
      repository: csaa/security-gauntlt
      tag: latest

  - name: timer
    type: time
    source:
      interval: 60m

jobs:
  - name: run-security-tests-e3
    plan:
    - get: git-securitytests-repo 
      trigger: false
    - get: securitytests-image
      trigger: false
    - get: timer
      trigger: true
    - task: run-tests-e3
      inputs:
      - name: git-securitytests-repo
      image: securitytests-image
      file: git-securitytests-repo/ci/check.yml
  - name: run-security-tests-e2
    serial: false
    plan:
    - aggregate:
      - get: git-securitytests-repo
        trigger: false
      - get: securitytests-image
        trigger: false
    - task: run-tests-e2
      config:
        platform: linux
        inputs:
        - name: git-securitytests-repo
        image: securitytests-image 
        run: 
          path: git-securitytests-repo/e2-SecurityTestCases.sh 
  - name: run-security-tests-e1
    serial: false
    plan:
    - aggregate:
      - get: git-securitytests-repo
        trigger: false
      - get: securitytests-image
        trigger: false
      - get: timer
        trigger: true
    - task: run-tests-e1
      config:
        platform: linux
        inputs:
        - name: git-securitytests-repo
        image_resource: 
          type: docker-image
          source:
            repository: csaa/security-gauntlt
            tag: latest
        run: 
          path: git-securitytests-repo/e1-SecurityTestCases.sh 
  - name: run-security-tests-prod
    serial: false
    plan:
    - aggregate:
      - get: git-securitytests-repo
        trigger: false
      - get: timer
        trigger: true
      - get: securitytests-image
    - task: run-tests-prod
      config:
        platform: linux
        inputs:
        - name: git-securitytests-repo
        image: securitytests-image 
        run: 
          path: git-securitytests-repo/prod-SecurityTestCases.sh 
  - name: run-security-tests-quote
    serial: false
    plan:
    - get: git-securitytests-repo
      trigger: false
    - get: timer
      trigger: true
    - get: securitytests-image
    - task: run-tests-quote
      config:
        platform: linux
        inputs:
        - name: git-securitytests-repo
        image: securitytests-image 
        run: 
          path: git-securitytests-repo/quote-SecurityTestCases.sh 
