resources:
  - name: resource-ci
    type: git
    source: 
      uri: https://github.com/aaa-ncnu-ie/securityTests.git
  - name: timer
    type: time
    source:
      interval: 60m

jobs:
  - name: securityTests
    plan:
    - get: resource-ci
    - task: run-tests
      file: resource-ci/ci/run-security-tests.yml
