resources:
  - name: git-securitytests-repo
    type: git
    source: 
      uri: https://github.com/aaa-ncnu-ie/securityTests.git

  - name: git-securitychecks-repo
    type: git
    source:
      uri: https://github.com/aaa-ncnu-ie/securityChecks.git

  - name: securitychecks-image
    type: docker-image
    source:
      repository: tgbenson/securitychecks
      tag: latest

  - name: securitytests-image
    type: docker-image
    source:
      repository: tgbenson/securitychecks
      tag: latest

jobs:
  - name: run-security-checks-quote
    plan:
    - aggregate:
      - get: securitychecks-repo
        resource: git-securitychecks-repo
        trigger: false
      - get: securitychecks-image
        trigger: false
    - task: run-securitychecks-quote
      file: securitychecks-repo/ci/tasks/checkquote.yml
      image: securitychecks-image
      params: 
        DATADOG_APIKEY: 8a91bd828137db6e599e3932c20ef336
        DATADOG_APPKEY: 249629b031233b4c14fd129cf74c03bebb77b8e8
        URLS: quoteMasterURLList.txt
        APP: quote
        SERVER: quote.ds-csaa.io
        ACCESS: quoteAccessControl.txt
        UNENCRYPT: quoteUnencryptControl.txt
  - name: run-security-checks-prod
    serial: true
    plan:
    - aggregate:
      - get: git-securitychecks-repo
        trigger: false
      - get: securitychecks-image
        trigger: false
    - task: run-securitychecks-prod
      config:
        platform: linux
        inputs:
         - name: securitychecks-repo
        image: securitychecks-image
        params: 
          DATADOG_APIKEY: 8a91bd828137db6e599e3932c20ef336
          DATADOG_APPKEY: 249629b031233b4c14fd129cf74c03bebb77b8e8
          URLS: csaaMasterURLList.txt
          APP: prod
          SERVER: csaa-insurance.aaa.com 
          ACCESS: csaaAccessControl.txt
          UNENCRYPT: csaaUnencryptControl.txt
        run:
          path: git-securitychecks-repo/securityChecks.sh
  - name: run-security-tests-e3
    plan:
    - aggregate: 
      - get: git-securitytests-repo 
        trigger: false
      - get: securitytests-image
        trigger: false
    - task: run-tests-e3
      config:
        platform: linux
        inputs:
        - name: git-securitytests-repo
        image: securitytests-image
        run: 
          path: /opt/securityTests/e3-SecurityTestCases.sh
  - name: run-security-tests-e2
    plan:
    - aggregate:
      - get: git-securitytests-repo
        trigger: false
      - get: securitytests-image
        trigger: false
    - task: run-tests-e2
      config:
        platform: linux
        inputs:
        - name: git-securitytests-repo
        image: securitytests-image
        run: 
          path: git-securitytests-repo/e2-SecurityTestCases.sh
